{
 "title": "OSMC - Monitoring Calico Components",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Nodes without Active Calico nodes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info) - count(felix_cluster_num_hosts)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TYPHA - CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"typha_metrics\"}[30s]) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TYPHA - 99%ile Breadcrumb Size",
   "type": "timeseries",
   "description": "Internally, Typha stores datastore changes as a series of blocks called breadcrumbs.\nThe default maximum size of a block is 100 so, if Typha is consistently generating size-100 blocks it may be overloaded.",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (instance) (typha_breadcrumb_size{quantile=\"0.99\"})",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "TYPHA - 99%ile Client fall-behind",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "max by (instance) (typha_client_latency_secs{quantile='0.99'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TYPHA - Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"typha_metrics\"}\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TYPHA - Non-blocking breadcrumb fraction",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 6 },
   "targets": [
    {
     "expr": "(sum by (instance) (rate(typha_breadcrumb_non_block[30s])))/((sum by (instance) (rate(typha_breadcrumb_non_block[30s])))+(sum by (instance) (rate(typha_breadcrumb_block[30s]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TYPHA - 99%ile Client Ping Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "max by (instance) (typha_ping_latency{quantile=\"0.99\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "FELIX - Active Calico nodes",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(felix_cluster_num_hosts)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "FELIX graph update time (Quantile 0.99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "felix_calc_graph_update_time_seconds{quantile=\"0.99\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FELIX - Dataplane apply time (Quantile 0.99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "felix_int_dataplane_apply_time_seconds{quantile=\"0.99\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FELIX - Log Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "targets": [
    { "expr": "rate(felix_log_errors[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Datastore Updates Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(typha_updates_total[30s]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}